spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:static/sqlite/Database.db
  mail:
    host: smtp.qq.com
    username: 1847767524@qq.com
    password: uddrxdogvmlwcafj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
          enable: true
          required: true