spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:static/sqlite/Database.db
  mail:
    host: smtp.163.com
    username: sunyt32@163.com
    password: UBNNQBTSYBXAVQZF
    properties:
      mail:
        smtp:
          auth: true
          starttls:
          enable: true
          required: true