spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:static/sqlite/Database.db
  mail:
    host: smtp.163.com
    port: 465
    username: sunyt32@163.com
    password: UBNNQBTSYBXAVQZF
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

